version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-fitness_booking}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: ${BACKEND_PORT:-5000}
      DB_HOST: db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DB_NAME: ${POSTGRES_DB:-fitness_booking}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET:-supersecretkeyfordevelopment

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.client # Assuming a Dockerfile for serving static files
    ports:
      - "80:80"
    depends_on:
      - backend

vols:
  postgres_data:
